def run_gisette(party, gpuid):
    print(f"python src/algorithm/SplitNN.py -d gisette -c 2 -m acc -p {party} -sp imp -w 1.0 -s 0 -g {gpuid} > out/gisette_scale_test/gisette_imp_w1.0_party{party}_seed0.txt &")
    print(f"python src/algorithm/SplitNN.py -d gisette -c 2 -m acc -p {party} -sp imp -w 1.0 -s 1 -g {gpuid} > out/gisette_scale_test/gisette_imp_w1.0_party{party}_seed1.txt &")
    print(f"python src/algorithm/SplitNN.py -d gisette -c 2 -m acc -p {party} -sp imp -w 1.0 -s 2 -g {gpuid} > out/gisette_scale_test/gisette_imp_w1.0_party{party}_seed2.txt &")
    print(f"python src/algorithm/SplitNN.py -d gisette -c 2 -m acc -p {party} -sp imp -w 1.0 -s 3 -g {gpuid} > out/gisette_scale_test/gisette_imp_w1.0_party{party}_seed3.txt &")
    print(f"python src/algorithm/SplitNN.py -d gisette -c 2 -m acc -p {party} -sp imp -w 1.0 -s 4 -g {gpuid} > out/gisette_scale_test/gisette_imp_w1.0_party{party}_seed4.txt &")

def run_realsim(party, gpuid):
    print(f"python src/algorithm/SplitNN.py -d realsim -c 2 -m acc -p {party} -sp imp -w 1.0 -s 0 -g {gpuid} > out/realsim_scale_test/realsim_imp_w1.0_party{party}_seed0.txt &")
    print(f"python src/algorithm/SplitNN.py -d realsim -c 2 -m acc -p {party} -sp imp -w 1.0 -s 1 -g {gpuid} > out/realsim_scale_test/realsim_imp_w1.0_party{party}_seed1.txt &")
    print(f"python src/algorithm/SplitNN.py -d realsim -c 2 -m acc -p {party} -sp imp -w 1.0 -s 2 -g {gpuid} > out/realsim_scale_test/realsim_imp_w1.0_party{party}_seed2.txt &")
    print(f"python src/algorithm/SplitNN.py -d realsim -c 2 -m acc -p {party} -sp imp -w 1.0 -s 3 -g {gpuid} > out/realsim_scale_test/realsim_imp_w1.0_party{party}_seed3.txt &")
    print(f"python src/algorithm/SplitNN.py -d realsim -c 2 -m acc -p {party} -sp imp -w 1.0 -s 4 -g {gpuid} > out/realsim_scale_test/realsim_imp_w1.0_party{party}_seed4.txt &")

print()
run_gisette(2, 0)
print()
run_gisette(8, 1)
print()
run_gisette(32, 2)
print()
run_gisette(128, 3)
print()
run_gisette(512, 4)
print()
run_gisette(2048, 5)

print()
run_realsim(2, 6)
print()
run_realsim(8, 7)
print()
run_realsim(32, 0)
print()
run_realsim(128, 1)
print()
run_realsim(512, 2)
print()
run_realsim(2048, 3)